# Generated by Django 5.2.2 on 2025-08-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Majburiy Kanal',
                'verbose_name_plural': 'Majburiy Kanallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(help_text='Foydalanuvchining Telegram ID', max_length=50, unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(help_text='Foydalanuvchining ismi', max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(help_text='Foydalanuvchining familiyasi', max_length=50, verbose_name='Familiya')),
                ('phone_number', models.CharField(help_text='Foydalanuvchining telefon raqami', max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('telegram_username', models.CharField(blank=True, help_text='Foydalanuvchining Telegram foydalanuvchi nomi', max_length=50, null=True, verbose_name='Telegram foydalanuvchi nomi')),
                ('region', models.CharField(choices=[('tashkent', 'Toshkent'), ('samarkand', 'Samarqand'), ('bukhara', 'Buxoro'), ('andijan', 'Andijon'), ('fergana', "Farg'ona"), ('namangan', 'Namangan'), ('kashkadarya', 'Qashqadaryo'), ('surkhandarya', 'Surxondaryo'), ('khorezm', 'Xorazm'), ('navoi', 'Navoiy'), ('jizzakh', 'Jizzax'), ('sirdarya', 'Sirdaryo'), ('karakalpakstan', "Qoraqalpog'iston")], help_text='Foydalanuvchining yashash joyi', max_length=50, verbose_name='Yashash joyi')),
                ('age', models.PositiveIntegerField(help_text='Foydalanuvchining yoshi', verbose_name='Yosh')),
                ('profession', models.CharField(help_text='Foydalanuvchining kasbi yoki faoliyati', max_length=100, verbose_name='Kasb yoki faoliyat')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], help_text='Foydalanuvchining jinsi', max_length=1, verbose_name='Jins')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text="Foydalanuvchi ro'yxatdan o'tgan sana", verbose_name="Ro'yxatdan o'tgan sana")),
                ('referral_code', models.CharField(blank=True, help_text='Foydalanuvchining referral kodi (taklif qilish uchun)', max_length=50, null=True, unique=True, verbose_name='Referral kod')),
                ('referral_count', models.PositiveIntegerField(default=0, help_text='Foydalanuvchini taklif qilganlar soni', verbose_name='Taklif qilganlar soni')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Foydalanuvchi tasdiqlanganmi', verbose_name='Tasdiqlangan')),
                ('confirmation_date', models.DateTimeField(blank=True, help_text='Foydalanuvchi tasdiqlangan sana', null=True, verbose_name='Tasdiqlangan sana')),
                ('is_admin', models.BooleanField(default=False, help_text='Foydalanuvchi adminmi', verbose_name='Admin')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Foydalanuvchini kim tasdiqlagan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_users', to='bot.telegramuser', verbose_name='Tasdiqlovchi')),
                ('invited_by', models.ForeignKey(blank=True, help_text='Foydalanuvchini kim taklif qilgan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='bot.telegramuser', verbose_name='Taklif qiluvchi')),
            ],
            options={
                'verbose_name': 'Telegram Foydalanuvchisi',
                'verbose_name_plural': 'Telegram Foydalanuvchilari',
                'ordering': ['-registration_date'],
            },
        ),
    ]
