# Generated by Django 5.2.2 on 2025-08-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurslar',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
