# Generated by Django 5.2.2 on 2025-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatorychannel',
            name='is_telegram',
            field=models.BooleanField(blank=True, default=True, help_text='Kanal Telegrammi yoki boshqa platformami', null=True, verbose_name='Kanal Telegrammi yoki boshqa platformami'),
        ),
        migrations.AlterField(
            model_name='mandatorychannel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Kanal faolmi', verbose_name='Kanal faolmi'),
        ),
        migrations.AlterField(
            model_name='mandatorychannel',
            name='link',
            field=models.URLField(blank=True, help_text='Kanalga havola', null=True, verbose_name='Kanalga havola'),
        ),
        migrations.AlterField(
            model_name='mandatorychannel',
            name='name',
            field=models.CharField(help_text='Majburiy kanal nomi', max_length=100, verbose_name='Majburiy Kanal Nomi'),
        ),
        migrations.AlterField(
            model_name='mandatorychannel',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Telegram kanal ID', max_length=100, null=True, verbose_name='Telegram Kanal ID'),
        ),
    ]
