# Generated by Django 5.2.2 on 2025-08-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayment',
            name='payment_type',
            field=models.CharField(choices=[('KONKURS', "Konkurs to'lovi"), ('COURSE', "Kurs to'lovi"), ('DONATION', "Xayriya to'lovi")], default='REFERRAL', max_length=20, verbose_name="To'lov turi"),
        ),
    ]
