# Generated by Django 5.2.2 on 2025-08-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_referralpayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayment',
            name='screenshot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
