# Generated by Django 5.2.2 on 2025-08-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_referralpayment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Sovg'a nomi")),
                ('description', models.TextField(verbose_name="Sovg'alar haqida ma'lumotnoma")),
                ('image', models.ImageField(blank=True, help_text="Sovg'a uchun rasm (agar mavjud bo'lsa)", null=True, upload_to='gifts', verbose_name="Sovg'a rasmi")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Sovg'a qachon yaratilgan", verbose_name='Yaratilgan sana')),
                ('is_active', models.BooleanField(default=True, help_text="Sovg'a faolmi yoki yo'qmi", verbose_name='Faoliyat holati')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text="Sovg'a qachon yangilangan", verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Sovg'a",
                'verbose_name_plural': "Sovg'alar",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='bot_gifts_name_e0b30b_idx'), models.Index(fields=['is_active'], name='bot_gifts_is_acti_bb74a4_idx')],
            },
        ),
    ]
