# Generated by Django 5.2.2 on 2025-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_gifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferrerUpdateQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.CharField(max_length=50)),
                ('referrer_telegram_id', models.CharField(max_length=50)),
                ('user_level', models.CharField(max_length=20)),
                ('referrer_level', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('RESOLVED', 'Hal qilingan'), ('AUTO_REPLACED', 'Avtomatik almashtirilgan'), ('FAILED', 'Xatolik')], default='PENDING', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Referrer Yangilash Navbati',
                'verbose_name_plural': 'Referrer Yangilash Navbatlari',
                'indexes': [models.Index(fields=['is_processed', 'created_at'], name='bot_referre_is_proc_3a66bf_idx')],
            },
        ),
    ]
