# Generated by Django 5.2.2 on 2025-08-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_referrerupdatequeue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='level',
            field=models.CharField(choices=[('level_0', '0-bosqich'), ('level_1', '1-bosqich'), ('level_2', '2-bosqich'), ('level_3', '3-bosqich'), ('level_4', '4-bosqich'), ('level_5', '5-bosqich'), ('level_6', '6-bosqich'), ('level_7', '7-bosqich')], default=('level_0', '0-bosqich'), help_text='Foydalanuvchi darajasi', max_length=20, verbose_name='Foydalanuvchi darajasi'),
        ),
    ]
