# Generated by Django 5.2.5 on 2025-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_referralpayment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='inactive_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_looser',
            field=models.BooleanField(default=False, verbose_name='Yutqazuvchi'),
        ),
    ]
