# Generated by Django 5.2.5 on 2025-08-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_telegramuser_inactive_time_telegramuser_is_looser'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurslar',
            name='referral_payment_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name="Referral to'lovi miqdori"),
            preserve_default=False,
        ),
    ]
