# Generated by Django 5.2.5 on 2025-08-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_kurslar_referral_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
