# Generated by Django 5.2.5 on 2025-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_telegramuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='deadline_for_activation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
